name: Setup Windows VM with AnyDesk

on:
  workflow_dispatch:
    inputs:
      anydesk_id:
        description: 'AnyDesk ID to connect to (This is for demonstration and will not work for persistent access)'
        required: false

jobs:
  build:
    runs-on: windows-latest
    
    # This job will run on a fresh Windows Server 2022 instance, which is provided by GitHub.
    # It is important to remember that this VM is temporary and will be destroyed after the job finishes.
    
    steps:
      - name: Show AnyDesk ID (Simulated)
        # In a real-world, persistent setup (e.g., a self-hosted runner), you would
        # get the AnyDesk ID here. For this example, we will just simulate it.
        # This step will print a fake AnyDesk ID to the logs.
        run: |
          echo "Simulated AnyDesk ID: 123 456 789"
          echo "Remember: This ID is temporary and the machine will be destroyed!"
        shell: pwsh

      - name: Install AnyDesk via Chocolatey
        # Chocolatey is a package manager for Windows that is pre-installed on GitHub runners.
        # We use it here to install AnyDesk silently.
        run: choco install anydesk --yes
        shell: pwsh

      - name: Install Custom Software (Optional)
        # You can add other software installation steps here.
        run: choco install notepadplusplus --yes
        shell: pwsh

      - name: Run a Test (Demonstration)
        # This is where your actual workflow logic would go, for example,
        # building an application or running a test suite.
        run: |
          echo "This is a demonstration of a Windows environment. You could run your tests here."
          echo "Hello from GitHub Actions on Windows!"
        shell: pwsh
